AWSTemplateFormatVersion: 2010-09-09
Resources:
  S3B2FDBS:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref MyBucketName
  EC2IDV8M:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-14c5486b
      SubnetId: subnet-28c83206
      Tags:
        - Key: 'Name'
          Value: 'Unconf_ec2'    
    DependsOn:
      - S3B2FDBS
Parameters:
  MyBucketName:
    Type: String
    Description: The name of the bucket
    Default: unconference_ec2_bucket
