AWSTemplateFormatVersion: 2010-09-09

Resources:
  S3B2FDBS:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref MyBucketName

# Parameters can be referenced by the, and provide input data at Stack create time
Parameters:
  MyBucketName:
    Type: String
    Description: The name of the bucket
    Default: UnconferenceS3
